blueprint:
  name: Two-Way Volume Sync with Optional Nonlinear Scaling
  description:
    Synchronize volume between a virtual media player (e.g. Squeezelite)
    and a real amplifier, with optional nonlinear scaling (square root/square), volume
    capping, and loop prevention using state-based comparison and tolerance.
  domain: automation
  input:
    virtual_player:
      name: Virtual Media Player (control)
      description: Dummy or control-only media player (e.g. Squeezelite).
      selector:
        entity:
          domain:
            - media_player
          multiple: false
    real_player:
      name: Real Media Player (volume)
      description: The actual AVR or amp whose volume is controlled.
      selector:
        entity:
          domain:
            - media_player
          multiple: false
    scale_factor:
      name: Volume upper limit (scale)
      description:
        Multiplier used during volume transformation to cap the amp volume,  e.g.
        volume = control*scale.
      default: 0.7
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.01
          mode: slider
    lower_limit:
      name: Volume lower limit (offset)
      description:
        Offset used during volume transformation to offset the minimum volume, 
        such that volume >= offset. Achieved by volume = (control-cap)/(1-cap)
      default: 0.4
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.01
          mode: slider
    p:
      name: Scaling factor for nonlinear scaling (p)
      description: Scales volume for more natural progession, such that
        amplifier volume is pth root of virtual volume,  i.e.
        volume = (control ** 1/p) * cap. Default of 1 uses linear scaling.
      default: 1
      selector:
        number:
          min: 0.1
          max: 5
          step: 0.1
          mode: slider
  source_url: https://github.com/thebigspin/ha-blueprints/blob/main/two-way-volume.yaml
variables:
  scale_factor: !input scale_factor
  lower_limit: !input lower_limit
  p: !input p

  scale: "{{ float(scale_factor) }}"
  limit: "{{ float(lower_limit) }}"

  virtual_player: !input virtual_player
  virt: "{{ state_attr(virtual_player, 'volume_level') }}"

  # Forward transform: virt → real
  real_from_virt: >
    {{ (limit + (scale - limit) * (virt ** (1/p))) | round(2) }}

  real_player: !input real_player
  real: "{{ state_attr(real_player, 'volume_level') }}"

  # Inverse transform: real → virt
  virt_from_real: >
    {% set norm = (real - limit) / (scale - limit) %}
    {{ (norm ** p) | round(2) }}
triggers:
  - trigger: state
    entity_id: !input virtual_player
    attribute: volume_level
    id: virtual
  - trigger: state
    entity_id: !input real_player
    attribute: volume_level
    id: real
condition:
  - condition: template
    value_template: "{{ (real_scaled - virt) | abs > 0.005}}"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: virtual
        sequence:
          - action: media_player.volume_set
            target:
              entity_id: !input real_player
            data:
              volume_level: "{{ virt_scaled }}"
      - conditions:
          - condition: trigger
            id: real
        sequence:
          - action: media_player.volume_set
            target:
              entity_id: !input virtual_player
            data:
              volume_level: "{{ real_scaled }}"
mode: queued
